//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoMDB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoMDB.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ET.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dssd.
        /// </summary>
        internal static string CantSaveDeckErr {
            get {
                return ResourceManager.GetString("CantSaveDeckErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur.
        /// </summary>
        internal static string ColorText {
            get {
                return ResourceManager.GetString("ColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courante.
        /// </summary>
        internal static string CurrentRevision {
            get {
                return ResourceManager.GetString("CurrentRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck (*.xml)|*.xml.
        /// </summary>
        internal static string DeckFileFilter {
            get {
                return ResourceManager.GetString("DeckFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier de données {0} n&apos;a pu être trouvé. Veuillez vérifier que ce fichier se trouve dans le même répertoire que ce programme..
        /// </summary>
        internal static string ErrDatabaseNotFound {
            get {
                return ResourceManager.GetString("ErrDatabaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de données non trouvée.
        /// </summary>
        internal static string ErrDatabaseNotFoundTitle {
            get {
                return ResourceManager.GetString("ErrDatabaseNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du chargement du deck..
        /// </summary>
        internal static string ErrDeckLoadTitle {
            get {
                return ResourceManager.GetString("ErrDeckLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la sauvegarde du deck..
        /// </summary>
        internal static string ErrDeckSaveTitle {
            get {
                return ResourceManager.GetString("ErrDeckSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier de données {0} n&apos;a pu être chargé. Veuillez télécharger la dernière version de ce fichier..
        /// </summary>
        internal static string ErrInvalidDatabase {
            get {
                return ResourceManager.GetString("ErrInvalidDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de données invalide.
        /// </summary>
        internal static string ErrInvalidDatabaseTitle {
            get {
                return ResourceManager.GetString("ErrInvalidDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le contenu du fichier ne correspond pas à un deck WOMDB..
        /// </summary>
        internal static string ErrInvalidXmlDeckFile {
            get {
                return ResourceManager.GetString("ErrInvalidXmlDeckFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette version de la base de données requière au moins la version {0} du logiciel. La version courante du logiciel est {1}. Le programme risque de fonctionner incorrectement. Voulez-vous continuer ?.
        /// </summary>
        internal static string ErrMinimalSoftwareVersionRequired {
            get {
                return ResourceManager.GetString("ErrMinimalSoftwareVersionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions incompatibles.
        /// </summary>
        internal static string ErrMinimalSoftwareVersionRequiredTitle {
            get {
                return ResourceManager.GetString("ErrMinimalSoftwareVersionRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur !.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dsds.
        /// </summary>
        internal static string ErrSaveXmlDeck {
            get {
                return ResourceManager.GetString("ErrSaveXmlDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier de deck  {0} n&apos;a pu être sauvegardé..
        /// </summary>
        internal static string ErrXmlDeckFileNotFound {
            get {
                return ResourceManager.GetString("ErrXmlDeckFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardlist.txt.
        /// </summary>
        internal static string ExportDefaultFilename {
            get {
                return ResourceManager.GetString("ExportDefaultFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier texte (*.txt)|*.txt.
        /// </summary>
        internal static string ExportSaveDialogFilter {
            get {
                return ResourceManager.GetString("ExportSaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puissance.
        /// </summary>
        internal static string PowerText {
            get {
                return ResourceManager.GetString("PowerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entre {1} et {2}.
        /// </summary>
        internal static string RangeBetween {
            get {
                return ResourceManager.GetString("RangeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string RangeGreaterOrLesser {
            get {
                return ResourceManager.GetString("RangeGreaterOrLesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  : .
        /// </summary>
        internal static string SeparatorText {
            get {
                return ResourceManager.GetString("SeparatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition.
        /// </summary>
        internal static string SetText {
            get {
                return ResourceManager.GetString("SetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipe.
        /// </summary>
        internal static string TeamText {
            get {
                return ResourceManager.GetString("TeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pouvoir total : .
        /// </summary>
        internal static string TotalPowerText {
            get {
                return ResourceManager.GetString("TotalPowerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeText {
            get {
                return ResourceManager.GetString("TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte inconnue..
        /// </summary>
        internal static string UnknownCard {
            get {
                return ResourceManager.GetString("UnknownCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue - {0}.
        /// </summary>
        internal static string ViewFormTitle {
            get {
                return ResourceManager.GetString("ViewFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le deck a été modifié. Voulez-vous le sauvegarder?.
        /// </summary>
        internal static string WarnDeckModified {
            get {
                return ResourceManager.GetString("WarnDeckModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck modifié.
        /// </summary>
        internal static string WarnDeckModifiedTitle {
            get {
                return ResourceManager.GetString("WarnDeckModifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas ajouter de carte au deck car vous êtes en train de voir une ancienne version de celui-ci..
        /// </summary>
        internal static string WarnImpossibleToAddCard {
            get {
                return ResourceManager.GetString("WarnImpossibleToAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action impossible.
        /// </summary>
        internal static string WarnImpossibleToAddCardTitle {
            get {
                return ResourceManager.GetString("WarnImpossibleToAddCardTitle", resourceCulture);
            }
        }
    }
}
