//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3082
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGoT.AGoTDB {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGoT.AGoTDB.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AND.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à avg.
        /// </summary>
        internal static string AvgStatsText {
            get {
                return ResourceManager.GetString("AvgStatsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deck couldn&apos;t be saved!.
        /// </summary>
        internal static string CantSaveDeckErr {
            get {
                return ResourceManager.GetString("CantSaveDeckErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claim.
        /// </summary>
        internal static string ClaimText {
            get {
                return ResourceManager.GetString("ClaimText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cost or income.
        /// </summary>
        internal static string CostOrIncomeText {
            get {
                return ResourceManager.GetString("CostOrIncomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cost.
        /// </summary>
        internal static string CostText {
            get {
                return ResourceManager.GetString("CostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current.
        /// </summary>
        internal static string CurrentRevision {
            get {
                return ResourceManager.GetString("CurrentRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deck (*.xml)|*.xml.
        /// </summary>
        internal static string DeckFileFilter {
            get {
                return ResourceManager.GetString("DeckFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DOOMED.
        /// </summary>
        internal static string DoomedText {
            get {
                return ResourceManager.GetString("DoomedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database file {0} could not be found. Please make sure that file is in the same directory than this program..
        /// </summary>
        internal static string ErrDatabaseNotFound {
            get {
                return ResourceManager.GetString("ErrDatabaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database not found.
        /// </summary>
        internal static string ErrDatabaseNotFoundTitle {
            get {
                return ResourceManager.GetString("ErrDatabaseNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while loading a deck..
        /// </summary>
        internal static string ErrDeckLoadTitle {
            get {
                return ResourceManager.GetString("ErrDeckLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while saving a deck..
        /// </summary>
        internal static string ErrDeckSaveTitle {
            get {
                return ResourceManager.GetString("ErrDeckSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database file {0} could not be loaded. Please download the latest version of the database..
        /// </summary>
        internal static string ErrInvalidDatabase {
            get {
                return ResourceManager.GetString("ErrInvalidDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid database.
        /// </summary>
        internal static string ErrInvalidDatabaseTitle {
            get {
                return ResourceManager.GetString("ErrInvalidDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The content of the file is not a valid AGOTDB deck..
        /// </summary>
        internal static string ErrInvalidXmlDeckFile {
            get {
                return ResourceManager.GetString("ErrInvalidXmlDeckFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This version of the database requires at least the version {0} for the software. Current version of the software is {1}. The software may malfunction. Do you wish to continue?.
        /// </summary>
        internal static string ErrMinimalSoftwareVersionRequired {
            get {
                return ResourceManager.GetString("ErrMinimalSoftwareVersionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version mismatch.
        /// </summary>
        internal static string ErrMinimalSoftwareVersionRequiredTitle {
            get {
                return ResourceManager.GetString("ErrMinimalSoftwareVersionRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error!.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The deck file {0} could not be saved..
        /// </summary>
        internal static string ErrSaveXmlDeck {
            get {
                return ResourceManager.GetString("ErrSaveXmlDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The deck file {0} could not be found..
        /// </summary>
        internal static string ErrXmlDeckFileNotFound {
            get {
                return ResourceManager.GetString("ErrXmlDeckFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cardlist.txt.
        /// </summary>
        internal static string ExportDefaultFilename {
            get {
                return ResourceManager.GetString("ExportDefaultFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text file (*.txt)|*.txt.
        /// </summary>
        internal static string ExportSaveDialogFilter {
            get {
                return ResourceManager.GetString("ExportSaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Holy.
        /// </summary>
        internal static string HolyVirtueText {
            get {
                return ResourceManager.GetString("HolyVirtueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à House.
        /// </summary>
        internal static string HouseText {
            get {
                return ResourceManager.GetString("HouseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Icons.
        /// </summary>
        internal static string IconsText {
            get {
                return ResourceManager.GetString("IconsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Income.
        /// </summary>
        internal static string IncomeText {
            get {
                return ResourceManager.GetString("IncomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initiative.
        /// </summary>
        internal static string InitiativeText {
            get {
                return ResourceManager.GetString("InitiativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INT.
        /// </summary>
        internal static string IntrigueIconAbrev {
            get {
                return ResourceManager.GetString("IntrigueIconAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Learned.
        /// </summary>
        internal static string LearnedVirtueText {
            get {
                return ResourceManager.GetString("LearnedVirtueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à max.
        /// </summary>
        internal static string MaxStatsText {
            get {
                return ResourceManager.GetString("MaxStatsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MIL.
        /// </summary>
        internal static string MilitaryIconAbrev {
            get {
                return ResourceManager.GetString("MilitaryIconAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à min.
        /// </summary>
        internal static string MinStatsText {
            get {
                return ResourceManager.GetString("MinStatsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MULTIPLAYER.
        /// </summary>
        internal static string MultiplayerText {
            get {
                return ResourceManager.GetString("MultiplayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Noble.
        /// </summary>
        internal static string NobleVirtueText {
            get {
                return ResourceManager.GetString("NobleVirtueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OR.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à POW.
        /// </summary>
        internal static string PowerIconAbrev {
            get {
                return ResourceManager.GetString("PowerIconAbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GOLD.
        /// </summary>
        internal static string ProvidedGoldText {
            get {
                return ResourceManager.GetString("ProvidedGoldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INFLUENCE.
        /// </summary>
        internal static string ProvidedInfluenceText {
            get {
                return ResourceManager.GetString("ProvidedInfluenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INITIATIVE.
        /// </summary>
        internal static string ProvidedInitiativeText {
            get {
                return ResourceManager.GetString("ProvidedInitiativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} between {1} and {2}.
        /// </summary>
        internal static string RangeBetween {
            get {
                return ResourceManager.GetString("RangeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1} {2}.
        /// </summary>
        internal static string RangeGreaterOrLesser {
            get {
                return ResourceManager.GetString("RangeGreaterOrLesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set.
        /// </summary>
        internal static string SetText {
            get {
                return ResourceManager.GetString("SetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ShadowCost.
        /// </summary>
        internal static string ShadowCostText {
            get {
                return ResourceManager.GetString("ShadowCostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shadow.
        /// </summary>
        internal static string ShadowVirtueText {
            get {
                return ResourceManager.GetString("ShadowVirtueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strength.
        /// </summary>
        internal static string StrengthText {
            get {
                return ResourceManager.GetString("StrengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string TypeText {
            get {
                return ResourceManager.GetString("TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown card.
        /// </summary>
        internal static string UnknownCard {
            get {
                return ResourceManager.GetString("UnknownCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View - {0}.
        /// </summary>
        internal static string ViewFormTitle {
            get {
                return ResourceManager.GetString("ViewFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Virtues.
        /// </summary>
        internal static string VirtuesText {
            get {
                return ResourceManager.GetString("VirtuesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The deck has been modified. Do you want to save the changes?.
        /// </summary>
        internal static string WarnDeckModified {
            get {
                return ResourceManager.GetString("WarnDeckModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deck modified..
        /// </summary>
        internal static string WarnDeckModifiedTitle {
            get {
                return ResourceManager.GetString("WarnDeckModifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can&apos;t add a card to the deck because you&apos;re currently viewing an previous revision of it..
        /// </summary>
        internal static string WarnImpossibleToAddCard {
            get {
                return ResourceManager.GetString("WarnImpossibleToAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action forbidden.
        /// </summary>
        internal static string WarnImpossibleToAddCardTitle {
            get {
                return ResourceManager.GetString("WarnImpossibleToAddCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à War.
        /// </summary>
        internal static string WarVirtueText {
            get {
                return ResourceManager.GetString("WarVirtueText", resourceCulture);
            }
        }
    }
}
