//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidDB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndroidDB.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advancement.
        /// </summary>
        internal static string AdvancementText {
            get {
                return ResourceManager.GetString("AdvancementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda points.
        /// </summary>
        internal static string AgendaPointsText {
            get {
                return ResourceManager.GetString("AgendaPointsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avg.
        /// </summary>
        internal static string AvgStatsText {
            get {
                return ResourceManager.GetString("AvgStatsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANNED IN TOURNAMENT.
        /// </summary>
        internal static string BannedText {
            get {
                return ResourceManager.GetString("BannedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base link.
        /// </summary>
        internal static string BaseLinkText {
            get {
                return ResourceManager.GetString("BaseLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck couldn&apos;t be saved!.
        /// </summary>
        internal static string CantSaveDeckErr {
            get {
                return ResourceManager.GetString("CantSaveDeckErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        internal static string ClaimText {
            get {
                return ResourceManager.GetString("ClaimText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string CostText {
            get {
                return ResourceManager.GetString("CostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string CurrentRevision {
            get {
                return ResourceManager.GetString("CurrentRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the database is available. Do you want to download it?.
        /// </summary>
        internal static string DatabaseUpdateFound {
            get {
                return ResourceManager.GetString("DatabaseUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version found!.
        /// </summary>
        internal static string DatabaseUpdateFoundTitle {
            get {
                return ResourceManager.GetString("DatabaseUpdateFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck (*.xml)|*.xml.
        /// </summary>
        internal static string DeckFileFilter {
            get {
                return ResourceManager.GetString("DeckFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min deck size.
        /// </summary>
        internal static string DeckSizeText {
            get {
                return ResourceManager.GetString("DeckSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some cards couldn&apos;t be found in the Database (make sure you have updated the database with the latest Octgn sets)..
        /// </summary>
        internal static string ErrCardsNotFoundInOctgnDeckFile {
            get {
                return ResourceManager.GetString("ErrCardsNotFoundInOctgnDeckFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to connect to the database using the following connection string (please make sure the provider is correctly installed):
        ///{0}.
        /// </summary>
        internal static string ErrConnectingToDatabase {
            get {
                return ResourceManager.GetString("ErrConnectingToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the database.
        /// </summary>
        internal static string ErrConnectingToDatabaseTitle {
            get {
                return ResourceManager.GetString("ErrConnectingToDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database file {0} could not be found. Please make sure that file is in the same directory than this program..
        /// </summary>
        internal static string ErrDatabaseNotFound {
            get {
                return ResourceManager.GetString("ErrDatabaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not found.
        /// </summary>
        internal static string ErrDatabaseNotFoundTitle {
            get {
                return ResourceManager.GetString("ErrDatabaseNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Control+C to copy)
        ///{0}
        ///There was an error while updating the database files downloaded from {1}.
        ///
        ///Execution steps: 
        ///{2}
        ///
        ///Exception trace:
        ///{3}.
        /// </summary>
        internal static string ErrDatabaseUpdateFailed {
            get {
                return ResourceManager.GetString("ErrDatabaseUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Control+C to copy)
        ///{0}
        ///There was an error while retrieving the database update informations from {1}.
        ///Current file: {2}
        ///Exception trace:
        ///{3}.
        /// </summary>
        internal static string ErrDatabaseUpdateInformationsCouldntBeRetrieved {
            get {
                return ResourceManager.GetString("ErrDatabaseUpdateInformationsCouldntBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while retrieving the database update informations.
        /// </summary>
        internal static string ErrDatabaseUpdateInformationsTitle {
            get {
                return ResourceManager.GetString("ErrDatabaseUpdateInformationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating the database.
        /// </summary>
        internal static string ErrDatabaseUpdateTitle {
            get {
                return ResourceManager.GetString("ErrDatabaseUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading a deck..
        /// </summary>
        internal static string ErrDeckLoadTitle {
            get {
                return ResourceManager.GetString("ErrDeckLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving a deck..
        /// </summary>
        internal static string ErrDeckSaveTitle {
            get {
                return ResourceManager.GetString("ErrDeckSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database file {0} could not be loaded. Please download the latest version of the database..
        /// </summary>
        internal static string ErrInvalidDatabase {
            get {
                return ResourceManager.GetString("ErrInvalidDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid database.
        /// </summary>
        internal static string ErrInvalidDatabaseTitle {
            get {
                return ResourceManager.GetString("ErrInvalidDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of the file is not a valid AndroidDB deck..
        /// </summary>
        internal static string ErrInvalidXmlDeckFile {
            get {
                return ResourceManager.GetString("ErrInvalidXmlDeckFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of the database requires at least the version {0} for the software. Current version of the software is {1}. The software may malfunction. Do you wish to continue?.
        /// </summary>
        internal static string ErrMinimalSoftwareVersionRequired {
            get {
                return ResourceManager.GetString("ErrMinimalSoftwareVersionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version mismatch.
        /// </summary>
        internal static string ErrMinimalSoftwareVersionRequiredTitle {
            get {
                return ResourceManager.GetString("ErrMinimalSoftwareVersionRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No OCTGN sets found..
        /// </summary>
        internal static string ErrOctgnNotFound {
            get {
                return ResourceManager.GetString("ErrOctgnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets not found.
        /// </summary>
        internal static string ErrOctgnNotFoundTitle {
            get {
                return ResourceManager.GetString("ErrOctgnNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the OCTGN set: &apos;{0}&apos; (id: {1})
        ///The database TableSet doesn&apos;t contain the definition of that set (or if this is a chapter, the set containing that chapter): 
        ///Please update the databases manually to add the set definition..
        /// </summary>
        internal static string ErrOctgnSetNotDefinedInDatabase {
            get {
                return ResourceManager.GetString("ErrOctgnSetNotDefinedInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTCGN set not found in database.
        /// </summary>
        internal static string ErrOctgnSetNotDefinedInDatabaseTitle {
            get {
                return ResourceManager.GetString("ErrOctgnSetNotDefinedInDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deck file {0} could not be saved..
        /// </summary>
        internal static string ErrSaveXmlDeck {
            get {
                return ResourceManager.GetString("ErrSaveXmlDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following cards had no image and couldn&apos;t be added to the proxy document:.
        /// </summary>
        internal static string ErrUnprintedProxies {
            get {
                return ResourceManager.GetString("ErrUnprintedProxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deck file {0} could not be found..
        /// </summary>
        internal static string ErrXmlDeckFileNotFound {
            get {
                return ResourceManager.GetString("ErrXmlDeckFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardlist.txt.
        /// </summary>
        internal static string ExportDefaultFilename {
            get {
                return ResourceManager.GetString("ExportDefaultFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file (*.txt)|*.txt.
        /// </summary>
        internal static string ExportSaveDialogFilter {
            get {
                return ResourceManager.GetString("ExportSaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction.
        /// </summary>
        internal static string FactionText {
            get {
                return ResourceManager.GetString("FactionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder containing the card images doesn&apos;t exist.
        /// </summary>
        internal static string ImageFolderDoesntExist {
            get {
                return ResourceManager.GetString("ImageFolderDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not available..
        /// </summary>
        internal static string ImageNotAvailable {
            get {
                return ResourceManager.GetString("ImageNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Influence.
        /// </summary>
        internal static string InfluenceText {
            get {
                return ResourceManager.GetString("InfluenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string LinkText {
            get {
                return ResourceManager.GetString("LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        internal static string MaxStatsText {
            get {
                return ResourceManager.GetString("MaxStatsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string MinStatsText {
            get {
                return ResourceManager.GetString("MinStatsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octgn (*.o8d)|*.o8d.
        /// </summary>
        internal static string OctgnDeckFileFilter {
            get {
                return ResourceManager.GetString("OctgnDeckFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} between {1} and {2}.
        /// </summary>
        internal static string RangeBetween {
            get {
                return ResourceManager.GetString("RangeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string RangeGreaterOrLesser {
            get {
                return ResourceManager.GetString("RangeGreaterOrLesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I noticed the following error:.
        /// </summary>
        internal static string ReportCardErrorMessageBody {
            get {
                return ResourceManager.GetString("ReportCardErrorMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in card {0}.
        /// </summary>
        internal static string ReportCardErrorMessageTitle {
            get {
                return ResourceManager.GetString("ReportCardErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This card is on the tournament restricted list..
        /// </summary>
        internal static string RestrictedText {
            get {
                return ResourceManager.GetString("RestrictedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string SeparatorText {
            get {
                return ResourceManager.GetString("SeparatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string SetText {
            get {
                return ResourceManager.GetString("SetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string StrengthText {
            get {
                return ResourceManager.GetString("StrengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may add cards by double-clicking on them in the main window.
        /// </summary>
        internal static string TreeNodeAddCard {
            get {
                return ResourceManager.GetString("TreeNodeAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeText {
            get {
                return ResourceManager.GetString("TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown card.
        /// </summary>
        internal static string UnknownCard {
            get {
                return ResourceManager.GetString("UnknownCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown card type.
        /// </summary>
        internal static string UnknownCardType {
            get {
                return ResourceManager.GetString("UnknownCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files to {0}.
        /// </summary>
        internal static string UpdatingDB_CopyingFiles {
            get {
                return ResourceManager.GetString("UpdatingDB_CopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} to {1}.
        /// </summary>
        internal static string UpdatingDB_DownloadingFileTo {
            get {
                return ResourceManager.GetString("UpdatingDB_DownloadingFileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unziping file {0}.
        /// </summary>
        internal static string UpdatingDB_UnzipingFile {
            get {
                return ResourceManager.GetString("UpdatingDB_UnzipingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View - {0}.
        /// </summary>
        internal static string ViewFormTitle {
            get {
                return ResourceManager.GetString("ViewFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deck has been modified. Do you want to save the changes?.
        /// </summary>
        internal static string WarnDeckModified {
            get {
                return ResourceManager.GetString("WarnDeckModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck modified.
        /// </summary>
        internal static string WarnDeckModifiedTitle {
            get {
                return ResourceManager.GetString("WarnDeckModifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add a card to the deck because you&apos;re currently viewing an previous revision of it..
        /// </summary>
        internal static string WarnImpossibleToAddCard {
            get {
                return ResourceManager.GetString("WarnImpossibleToAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action forbidden.
        /// </summary>
        internal static string WarnImpossibleToAddCardTitle {
            get {
                return ResourceManager.GetString("WarnImpossibleToAddCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCTGN sets are not loaded. Do you want to load them?.
        /// </summary>
        internal static string WarnOctgnNotLoaded {
            get {
                return ResourceManager.GetString("WarnOctgnNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCTGN sets not loaded.
        /// </summary>
        internal static string WarnOctgnNotLoadedTitle {
            get {
                return ResourceManager.GetString("WarnOctgnNotLoadedTitle", resourceCulture);
            }
        }
    }
}
